import { Tooltip } from "../../../../interfaces/config/general/Tooltip.model";
import { FontStyle } from "../../enum/FontStyle.enum";
import { Mode } from "../../enum/Mode.enum";
import { TooltipAlign } from "../../enum/TooltipAlign.enum";
import { TooltipPosition } from "../../enum/TooltipPosition.enum";

export class TooltipImpl implements Tooltip{
    enabled: boolean = true;
    mode: Mode = Mode.NEAREST;
    intersect: boolean = true;
    position: TooltipPosition = TooltipPosition.NEAREST;
    backgroundColor: string = '#ccc';
    titleFontFamily: string = 'system-ui';
    titleFontSize: number = 12;
    titleFontStyle: FontStyle = FontStyle.NORMAL;
    titleFontColor: string = '#666';
    titleAlign: TooltipAlign = TooltipAlign.CENTER;
    titleSpacing: number = 2;
    titleMarginBottom: number = 6;
    bodyFontFamily: string = 'system-ui';
    bodyFontSize: number = 12;
    bodyFontStyle: FontStyle = FontStyle.NORMAL;
    bodyFontColor: string = '#666';
    bodyAlign: TooltipAlign = TooltipAlign.CENTER;
    bodySpacing: number = 2;
    footerFontFamily: string = 'system-ui';
    footerFontSize: number = 2;
    footerFontStyle: FontStyle = FontStyle.NORMAL;
    footerFontColor: string = '#666';
    footerAlign: TooltipAlign = TooltipAlign.CENTER;
    footerSpacing: number = 2;
    footerMarginTop: number = 6;
    xPadding: number = 6;
    yPadding: number = 6;
    caretPadding: number = 2;
    caretSize: number = 5;
    cornerRadius: number = 6;
    multiKeyBackground: string = '#666';
    displayColors: boolean = true;
    borderColor: string = '#000';
    borderWidth: number = 1;
    rtl: boolean = false;
}